### ISSUE TITLE
@testable import ExampleAppBinary doesn't work

### ISSUE THREAD

**Issue by mgrebenets** [airbnb/BuckSample#24] opened 2019-01-31 12:02 UTC
I've mentioned this issue on Slack channel, and wanted to try it with AirBnB's custom fork of `buck`.

Still no luck though.

Adding `@testable import ExampleAppBinary` to any of the tests, e.g. to `BuckSampleTests.swift` or `BuckSampleUITests.swift` causes this error:

```
Command failed with exit code 1.
stderr: App/UITests/BuckSampleUITests.swift:10:18: error: no such module 'ExampleAppBinary'
@testable import ExampleAppBinary
                 ^
```

While I can definitely find the `ExampleAppBinary` module with `find buck-out -name "*ExampleApp*"`

```
buck-out/gen/App/ExampleAppBinary#iphonesimulator-x86_64,swift-compile
buck-out/gen/App/ExampleAppBinary#iphonesimulator-x86_64,swift-compile/ExampleAppBinary.swiftmodule
buck-out/gen/App/ExampleAppBinary#iphonesimulator-x86_64,swift-compile/ExampleAppBinary-Swift.h
buck-out/gen/App/ExampleAppBinary#iphonesimulator-x86_64,swift-compile/ExampleAppBinary.o
```

I can't use it in Unit or UI tests though.

The original issue is here: https://github.com/facebook/buck/issues/2074

P.S.
I know it's open source and all that, but I don't have the time and code base knowledge to locate the change that removed this functionality and revert just the bits that make app module imports work again.

Since this is the only up-to-date buck demo of mix-n-match project there is (🥇), I thought raising it here would draw some attention to it.

Also, I though most of AirBnB's changes made it to master already... At least I was able to use `import` statements in our mix-n-match project with `modular=True` flag using current `master`.

**Comment by thedavidharris** [comment] 2019-02-27 22:11
Actually running into this issue on our large projects we're toying with moving to Buck. Didn't realize there was a Slack channel, I'll have to figure out if we can get our emails added to it.

We'll _probably_ just undo the need for the `@testable` which is probably not ideal but given that these are our top-level targets anyway and we can set the visibility, it shouldn't do much hard.

As an aside, this repo has been **incredibly** helpful. I'll see if I can contribute back to this a few of the modifications (additive) we've made if that's alright, and sometime in the next few weeks we'll probably see if we can get this working with a Watch app and extension that might be a useful example as well.

**Comment by mgrebenets** [comment] 2019-02-28 04:00
yep. `@testable` just makes `internal` declaration from the module visible to tests code. 

The main issue is that main app module is “invisible”. 

The change was done by Uber guys afaik, and their app is so modularised that they don’t ever have the need to import main app target. Looks like AirBnB also achieves this state :)

The rest of us with less modular apps have the issue :)

**Comment by dfed** [comment] 2019-02-28 06:22
I believe you can get `@testable` imports working by wrapping your application’s code in a library, and then having your main binary depend on your library (note that your binary will need to include a single empty source file to get Xcode project generation working). I can submit a PR for this next week. The difference in the Buck files should hopefully be pretty small, with no impact on code.

**Comment by dfed** [comment] 2019-02-28 06:28
Also, @thedavidharris: we’d love for you to contribute back your learnings! It’s best to file Issues first so we can get a sense of what you’re working on before a PR lands, but we can chat at PR-time too. Glad the repo has been helpful!

Regarding a watch app: I’ve hit a wall on how to get Watch to work properly in a generated project (we have it working in Buck CLI though). Happy to discuss that more over Slack or twitter – my handle is in my github profile, and my DMs are open. If you get a watch app working I’ll be thrilled 😀

**Comment by mgrebenets** [comment] 2019-02-28 11:58
Would wrapping app code into a library be a considerable amount of work?
It feels like it will be for an app like ours.

**Comment by dfed** [comment] 2019-02-28 12:13
It shouldn’t be much work. The steps would be:

1. Create a library with the same name as your current binary
1. Change the name of your current binary (i.e append `App` to it)
1. Move the `srcs`, `deps`, and other fields you have (compiler flags, etc) from your binary into your library
1. Set the `deps` of your binary to be an array with just your library in it
1. Set the `srcs` of  your binary to be an array with just a single, empty swift file in it (if you have no swift, you can use an ObjC file).

I think those are all the steps. I’ll update this list when I put the PR out next week. If someone would prefer to try the above steps on this repo and put a PR out, that’d be fine too. Only reason I’m not doing this work sooner is I am away from a computer until Monday.

**Comment by dfed** [comment] 2019-03-04 22:19
The above steps worked. See the PR!

**Closed** 2019-03-04 22:18 UTC

**Comment by dfed** [comment] 2019-03-12 04:44
Closing the loop on the watch app @thedavidharris, check out https://github.com/airbnb/BuckSample/pull/48. @qyang-nj got the watch app working!

**Comment by hendych** [comment] 2019-04-04 13:16
@dfed This workaround is working, but in my case, this will generate a huge `xctest` bundle inside `buck-out` because the whole app defined through `deps` will be copied into the `xctest` bundle.

This is different when built through Xcode.

**Comment by dfed** [comment] 2019-04-04 13:51
Is having a large`xctest` bundle problematic? I’d also expect that Xcode will have the same issue.

The reason the entire app + dependencies get put in a test bundle that depends on the app is because Buck uses static libraries rather than dynamic frameworks.

I think what you are seeing is correct/expected behavior.

**Comment by hendych** [comment] 2019-04-04 14:15
When I use xcode, the xctest bundle doesnt include the app code.
I think it wont be an issue when the app is small. But it will, when the app is big.

For my case, I have huge ipa size, making the build buck bottleneck on copying resources and linking.
Even when only incremental build, the compile took 10s but the linking and copy step took 4 min. 😂

**Comment by dfed** [comment] 2019-04-04 14:46
> When I used Xcode

Do you mean you are using Xcode via a project created with `buck project`? Or are you using a manually managed project that uses dynamic frameworks?

We also have a large (I think we’re over 200mb with debut symbols) ipa size. I don’t think we’ve seen this issue, but maybe the issue is obviated by the use of a cache?

**Comment by hendych** [comment] 2019-04-04 15:02
> 
> Do you mean you are using Xcode via a project created with `buck project`? Or are you using a manually managed project that uses dynamic frameworks?
No, I was comparing it with the usual xcode project. (without xcode gen).

On my second investigation, I found that my project didn't use @testable import before. But, when I see the `DerivedData` folder, it did include some `.o` and `.dep` from the app source code, when the test case did import it.

>
> We also have a large (I think we’re over 200mb with debug symbols) ipa size. I don’t think we’ve seen this issue, but maybe the issue is obviated by the use of a cache?

So in your case, do you use xctest bundle? If you do, is it also around 200MB?

**Comment by dfed** [comment] 2019-04-04 15:16
> No, I was comparing it with the usual xcode project. (without xcode gen).

Makes sense. Buck’s build system is quite different from a standard manually managed Xcode project configuration. The biggest difference for us was Buck’s use of static libraries rather than dynamic frameworks. If you are interested in dynamic frameworks, check out the work we’re doing here: https://github.com/airbnb/BuckSample/pull/52

> On my second investigation, I found that my project didn't use @testable import before.

I’d be surprised if `@testable` were causing significant binary-size bloat. But I’ve been wrong before 😬

> So in your case, do you use xctest bundle?

Our Buck configuration matches this repo’s configuration. We use Buck’s `apple_test` both here and in our repo.

> If you do, is it also around 200MB?

Our main application’s test bundle is certainly larger than our main binary.

The biggest difference between dynamic frameworks and static libs is that resources (think images or other large non-code assets) are copied into the executable that depends on the static lib. With dynamic frameworks, resources stay in the dynamic framework’s bundle, allowing those resources to be shared (not copied) between different targets/binaries that rely on the same framework. Hopefully that helps clarify.

**Comment by hendych** [comment] 2019-04-04 15:27
> 
> The biggest difference between dynamic frameworks and static libs is that resources (think images or other large non-code assets) are copied into the executable that depends on the static lib. With dynamic frameworks, resources stay in the dynamic framework’s bundle, allowing those resources to be shared (not copied) between different targets/binaries that rely on the same framework. Hopefully that helps clarify.

I see, thanks a lot for your explanation! This did clarify things for me. Pardon a noob like me. :)

**Comment by dfed** [comment] 2019-04-04 15:47
No worries! I learned this all about 4 months ago, so I’m happy to help a fellow noob 😄

Another detail about the differences between dynamic frameworks and static libraries, but this time related to runtime instead of build time. Apple’s dynamic library loader is super slow, per a WWDC talk a few years back. It gets exponentially slower with each dynamic library loaded – Apple recommends having no more than 6 dynamic libraries for optimal launch time. Static libraries, on the other hand, have no impact on launch time. So it is preferable to use static libraries whenever possible from an end-customer POV.

**Comment by dfed** [comment] 2019-04-06 17:51
@hendych you might be interested in this thread: https://github.com/airbnb/BuckSample/pull/66#discussion_r272802793
